# Generated by Django 4.2.10 on 2024-03-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30, null=True)),
                ('Last_name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
