# Generated by Django 4.2.10 on 2024-03-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_appointment_delete_std'),
    ]

    operations = [
        migrations.CreateModel(
            name='std',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
