# Generated by Django 4.2.10 on 2024-03-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_std'),
    ]

    operations = [
        migrations.DeleteModel(
            name='std',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
    ]
